NumPy-数组间运算

In [1]:
#导入NumPy包
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

#加
print(arr+1)
#乘
print(arr*10)
#除
print(arr/10)

'''
注意：python list无法实现以上运算。
'''

[[2 3 4 5]
 [6 7 8 9]]
[[10 20 30 40]
 [50 60 70 80]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]


'\n注意：python list无法实现以上运算。\n'

In [3]:
#NumPy广播机制

'''
广播原则：
如果两个数组的后缘维度的轴长度相同或其中一方的轴长度为1，则认为它们是广播兼容的，广播会在缺失的和长度为1的维度上进行。
比如形状为(1,2,3)的三维数组和形状为(2,3)，(2,1)和(1,3)的二维数组是广播兼容的。
'''

arr1=np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
arr2=np.array([[1],[2]])

print(np.shape(arr1))
print(np.shape(arr2))

print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)

(2, 6)
(2, 1)
[[ 2  3  4  5  6  7]
 [ 9 10 11 12 13 14]]
[[ 1  2  3  4  5  6]
 [14 16 18 20 22 24]]
[[1.  2.  3.  4.  5.  6. ]
 [3.5 4.  4.5 5.  5.5 6. ]]
