NumPy-数组的属性

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#生成n维数组
score=np.array([[80,89,86,67,79],
                [78,97,89,67,81],
                [90,94,78,67,74],
                [91,91,90,67,69],
                [76,87,75,67,86],
                [70,79,84,67,84],
                [94,92,93,67,64],
                [86,85,83,67,80]])

In [3]:
print(score)
print(type(score))

[[80 89 86 67 79]
 [78 97 89 67 81]
 [90 94 78 67 74]
 [91 91 90 67 69]
 [76 87 75 67 86]
 [70 79 84 67 84]
 [94 92 93 67 64]
 [86 85 83 67 80]]
<class 'numpy.ndarray'>


In [4]:
#对比NumPy数组和python list的运算效率

#导入random和time包
import random
import time

#生成列表
python_list=[]

for i in range(1000000):
    python_list.append(random.random())

#生成NumPy数组
ndarray_list=np.array(python_list)

#python list求和并记录运算时间
t1=time.time()
a=sum(python_list)
t2=time.time()
d1=t2-t1

#ndarray求和
t3=time.time()
b=np.sum(ndarray_list)
t4=time.time()
d2=t4-t3

#对比运算时间
print('\n',d1,'\n',d2)


 0.007978677749633789 
 0.0029921531677246094


In [5]:
'''
NumPy数组的优势：
（1）存储方式：list支持不同类型的元素，通用性强，但是因此导致运算速度较慢，而ndarray只支持相同类型的元素，运算速度快；
（2）并行运算：ndarray支持并行化向量运算；
（3）底层语言：NumPy包的底层语言是C语言，不受Python解释器的限制。
'''

'\nNumPy数组的优势：\n（1）存储方式：list支持不同类型的元素，通用性强，但是因此导致运算速度较慢，而ndarray只支持相同类型的元素，运算速度快；\n（2）并行运算：ndarray支持并行化向量运算；\n（3）底层语言：NumPy包的底层语言是C语言，不受Python解释器的限制。\n'

In [6]:
#NumPy数组的属性

#数组的形状
print(score.shape)

#数组的维度
print(score.ndim)

#数组的元素数量
print(score.size)

#数组的类型，如果生成数组时没有指定类型，则整数数组默认类型为int64，浮点数数组默认类型为float64
print(score.dtype)

#数组的大小（单位：字节）
print(score.itemsize)

(8, 5)
2
40
int32
4


In [7]:
#NumPy数组的形状

#一维数组
a=np.array([1,2,3,4])
#二维数组
b=np.array([[1,2,3],[4,5,6]])
#三维数组
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print('\n',a.shape,'\n',b.shape,'\n',c.shape)


 (4,) 
 (2, 3) 
 (2, 2, 3)


In [8]:
#NumPy数组的类型
'''
如果生成数组时不指定类型，则整数数组的类型是int64，浮点是数组的类型是float64。
'''

#创建数组的时指定类型
#方法1
print(np.array([1.1, 2.2, 3.3], dtype='float32'))
#方法2
print(np.array([1.1, 2.2, 3.3], dtype=np.float32))

#字符串型数组（不常用，因为NumPy一般不用于处理字符串）
print(np.array(['Alpha', 'Beta', 'Gamma'], dtype=np.string_))

[1.1 2.2 3.3]
[1.1 2.2 3.3]
[b'Alpha' b'Beta' b'Gamma']
