NumPy-统计运算

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#案例：随机生成8只股票2周的交易日涨幅数据

#生成形状为(8,10)的标准正态随机数组
stock_change=np.random.normal(loc=0,scale=1,size=(8,10))
print(stock_change)

[[-1.08793601e+00  2.31370200e-02  3.78295799e-01  1.51200136e+00
   1.18156711e+00  2.61187137e-01 -2.48206531e-01  1.44535556e+00
  -1.03343282e+00  1.95686078e-01]
 [-1.90772242e+00 -2.37048394e-01  1.56259549e+00  4.59538712e-01
  -7.28467288e-01  1.98571842e+00 -1.51114023e+00 -1.54547653e+00
  -3.76236541e-01 -4.76263345e-01]
 [ 2.23186922e+00 -2.04462599e-01 -8.77587616e-01  9.41667677e-01
   3.28038895e-01  2.83978636e-01  3.75977293e-01 -8.61823916e-01
   5.56565889e-01 -1.91255469e-01]
 [-3.06343872e-01 -9.47277128e-01 -2.82112508e-01 -1.21529151e+00
   1.95831069e-01  5.08904608e-01 -1.22028886e-01 -1.81814847e+00
  -6.16201394e-01  3.29311456e-01]
 [ 6.41211930e-01 -3.17246039e-01 -1.67375605e+00 -1.07773032e+00
  -2.03387754e-01 -1.91138019e+00 -1.52664076e+00 -4.81128589e-01
  -8.27380440e-01 -2.17927560e-01]
 [-8.59179888e-01  1.45556167e+00 -1.11066554e+00 -4.95159210e-01
   7.41148061e-01  4.67563007e-02  1.38699155e+00  5.44065589e-01
   3.92567100e-01 -2.86434013e-04

In [3]:
#前四只股票前四天的最大涨幅

array=stock_change[:4,:4]
print(array)

#.max()
print(array.max())

#np.max()
print(np.max(array))

[[-1.08793601  0.02313702  0.3782958   1.51200136]
 [-1.90772242 -0.23704839  1.56259549  0.45953871]
 [ 2.23186922 -0.2044626  -0.87758762  0.94166768]
 [-0.30634387 -0.94727713 -0.28211251 -1.21529151]]
2.231869218867238
2.231869218867238


In [4]:
#行、列最值

#前4只股票第1天的最大涨幅
#列最大值（轴参数设置为0）
print(array.max(axis=0))

#前4天第1只股票的最大涨幅
#行最大值（轴参数设置为1）
print(np.max(array,axis=1))

[2.23186922 0.02313702 1.56259549 1.51200136]
[ 1.51200136  1.56259549  2.23186922 -0.28211251]


In [5]:
#最值索引

#前4天第1只股票的最大涨幅的索引值（从0开始计算）
np.argmax(array, axis=1)

array([3, 2, 0, 2], dtype=int64)