NumPy-数组的类型转换和去重

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#案例：随机生成8只股票2周的交易日涨幅数据

#生成形状为(8,10)的标准正态随机数组
stock_change=np.random.normal(loc=0,scale=1,size=(8,10))
print(stock_change)

[[ 0.3673164   1.11701367  0.59900347 -1.63575254  0.92726691  1.78770256
   0.23636704 -0.51392777  0.17250503  0.58604029]
 [ 0.77116636 -0.39642322 -0.63001329 -0.13083647 -0.36755557 -1.66833671
  -0.29382363 -0.08731849 -0.9598559   1.66941733]
 [ 0.41364787 -1.19441922  1.2748335   0.42040674  0.44001274 -0.61829358
   0.64353463 -0.60128354  0.29623584 -1.45116206]
 [-0.3317491   2.43719062  0.42857804  0.86941232  1.28812156  0.36156558
   0.29198522 -1.09387939  0.25086863  1.43119735]
 [ 0.27265976 -2.44396953  0.63388413  1.27719094  0.48596615 -0.30139939
  -0.5801638  -0.20359254 -0.6730446   0.00933795]
 [ 1.04344172  0.98198229  0.35376427 -0.17678447 -0.62893938  0.07782625
  -0.47430781 -0.97961059 -0.7450618  -0.43053945]
 [-1.29653918  1.13340312 -0.29177387 -0.833533   -0.27401544  0.98581956
   0.36169401 -1.3928112   0.89946872 -0.29013165]
 [ 0.51352404  1.79555242 -0.53613266 -0.04606277  1.92484619 -1.12696073
  -0.52286689  0.17581277  1.83610167 -1.58986485]]

In [3]:
#转换为32位整型
stock_change.astype('int32')

array([[ 0,  1,  0, -1,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  1],
       [ 0, -1,  1,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  2,  0,  0,  1,  0,  0, -1,  0,  1],
       [ 0, -2,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  1,  0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  1,  0,  0,  1, -1,  0,  0,  1, -1]])

In [4]:
#转化为bytes
stock_change.tostring()

b'\xbb\xcf\'\xa3\x1c\x82\xd7?w\xc90\xbaI\xdf\xf1?\xf7F\xc7Q\t+\xe3?\x9a\xa5K\xdc\n,\xfa\xbf\x95\xb93\xa7+\xac\xed?xJ\x10\x00n\x9a\xfc?\xd7\x1a\xcaoFA\xce?\xe2\x06M\xa5\x18r\xe0\xbf\xa6\xf3\x05\x11\xa5\x14\xc6?\xf5O\xe7\x92\xd7\xc0\xe2?\xbd\x9d\xd4\x13e\xad\xe8?\x06\xdcw\x84\xff^\xd9\xbfJ\x12\xe7\xa0\x11)\xe4\xbf\x13\x95\xa0\xd3?\xbf\xc0\xbf\xbe\xac*\xcd\x07\x86\xd7\xbf"\x03\xb5\xd6\x81\xb1\xfa\xbf-\xf5u\x9e\x01\xce\xd2\xbf\xedJ\x17;\x81Z\xb6\xbf\x82\xa6\xb1\xb9#\xb7\xee\xbfy\xb6P\xf3\xee\xb5\xfa?\xd1\x85:\xea4y\xda?\x10^\xceTW\x1c\xf3\xbf\xd4\x04\xbc\xd0\xb7e\xf4?\x19\x85u\xa7\xf1\xe7\xda?N\xdeu6+)\xdc? \x96\xe4\x9e\x0f\xc9\xe3\xbf\xcdD\x17\xf1\xd5\x97\xe4?\ts\xae\xf9\xb6=\xe3\xbfz\x8b\n,\x87\xf5\xd2?6\x17\x14\xb4\xf57\xf7\xbf\xa8\x06{\x8e`;\xd5\xbfm\xa7\xc0\xcb]\x7f\x03@\x87\xd3\xea\x96\xd2m\xdb?\xcb\x87\xa5\xca9\xd2\xeb?\xf7\xde\x87Z%\x9c\xf4?p4|\xf5\xe3#\xd7?\xee2\x81\xca\xe2\xaf\xd2?u\x19\xc9\xad\x87\x80\xf1\xbf\xf2\xe4{H;\x0e\xd0?\xee1}1/\xe6\xf6?DN\x06\xecAs\xd1?\x1e\x07\xf7\xe4?

In [5]:
#数组的去重

array=np.array([[1,2,3,4],[3,4,5,6]])
print(array)
#np.unique()
array1=np.unique(array)
print(array1)
#一维化后set()
array2=set(array.flatten())
print(array2)

[[1 2 3 4]
 [3 4 5 6]]
[1 2 3 4 5 6]
{1, 2, 3, 4, 5, 6}
