NumPy-数组的切片索引和形状修改

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#案例：随机生成8只股票2周的交易日涨幅数据

#生成形状为(8,10)的标准正态随机数组
stock_change=np.random.normal(loc=0,scale=1,size=(8,10))
print(stock_change)

[[ 0.23663317  0.03488579  0.35633464  1.13028114  0.6015624   0.39097332
   0.04637329  1.77251388  0.18406849 -0.30681789]
 [-0.32267767 -1.1431804  -0.79222112 -0.05054762  0.31163214 -1.47027098
  -0.0133358   0.4303031   2.35476663 -0.25158349]
 [-1.03822626  0.92226543  0.25972792 -0.45337474  0.44063958  0.74478827
  -0.45848981  1.13889807 -0.3113159   2.33507508]
 [ 0.89605235  0.5250052  -0.12929875 -1.20058572  0.81434476  0.24637811
  -1.55279182 -0.02552282 -0.22109037 -0.77157018]
 [ 0.53087326 -0.40326097 -2.06977153  0.5430819   2.80880493  1.11240915
  -0.33263886 -0.92186257  0.09788457  0.86054786]
 [-0.98554366  1.00046056 -0.18483511  1.3025589  -0.46337703 -1.07795541
   0.60416388 -0.09395627  1.33481531  0.17421221]
 [ 0.76928918  0.13996727  0.15429646  0.00824792  2.43488565 -0.50830003
   1.35430645  0.38894251  0.30898608 -1.77646276]
 [ 1.91530967  0.21214434 -0.34588212  2.41704809  1.2947494  -0.12419127
   0.03973829  2.26057623  0.64494489  2.50257072]]

In [3]:
#获取第一个股票的前3个交易日的涨跌幅数据
#切片第1列前3行
print(stock_change[0,0:3])

[0.23663317 0.03488579 0.35633464]


In [4]:
#三维数组索引
a1=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(a1,'\n',a1.shape)
#索引元素10（第2个二维数组，第1行，第3列）并修改
a1[1,0,2]=0
print(a1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]] 
 (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9  0]
  [11 12 13]]]


In [5]:
#.reshape()（不改变元素顺序,返回改变后的数组，但不改变原来的数组）
stock_change.reshape((10, 8))

array([[ 0.23663317,  0.03488579,  0.35633464,  1.13028114,  0.6015624 ,
         0.39097332,  0.04637329,  1.77251388],
       [ 0.18406849, -0.30681789, -0.32267767, -1.1431804 , -0.79222112,
        -0.05054762,  0.31163214, -1.47027098],
       [-0.0133358 ,  0.4303031 ,  2.35476663, -0.25158349, -1.03822626,
         0.92226543,  0.25972792, -0.45337474],
       [ 0.44063958,  0.74478827, -0.45848981,  1.13889807, -0.3113159 ,
         2.33507508,  0.89605235,  0.5250052 ],
       [-0.12929875, -1.20058572,  0.81434476,  0.24637811, -1.55279182,
        -0.02552282, -0.22109037, -0.77157018],
       [ 0.53087326, -0.40326097, -2.06977153,  0.5430819 ,  2.80880493,
         1.11240915, -0.33263886, -0.92186257],
       [ 0.09788457,  0.86054786, -0.98554366,  1.00046056, -0.18483511,
         1.3025589 , -0.46337703, -1.07795541],
       [ 0.60416388, -0.09395627,  1.33481531,  0.17421221,  0.76928918,
         0.13996727,  0.15429646,  0.00824792],
       [ 2.43488565, -0.50830003

In [6]:
#.resize(不改变元素顺序,无返回值，改变原来的数组)
stock_change.resize((10, 8))
print(stock_change)

[[ 0.23663317  0.03488579  0.35633464  1.13028114  0.6015624   0.39097332
   0.04637329  1.77251388]
 [ 0.18406849 -0.30681789 -0.32267767 -1.1431804  -0.79222112 -0.05054762
   0.31163214 -1.47027098]
 [-0.0133358   0.4303031   2.35476663 -0.25158349 -1.03822626  0.92226543
   0.25972792 -0.45337474]
 [ 0.44063958  0.74478827 -0.45848981  1.13889807 -0.3113159   2.33507508
   0.89605235  0.5250052 ]
 [-0.12929875 -1.20058572  0.81434476  0.24637811 -1.55279182 -0.02552282
  -0.22109037 -0.77157018]
 [ 0.53087326 -0.40326097 -2.06977153  0.5430819   2.80880493  1.11240915
  -0.33263886 -0.92186257]
 [ 0.09788457  0.86054786 -0.98554366  1.00046056 -0.18483511  1.3025589
  -0.46337703 -1.07795541]
 [ 0.60416388 -0.09395627  1.33481531  0.17421221  0.76928918  0.13996727
   0.15429646  0.00824792]
 [ 2.43488565 -0.50830003  1.35430645  0.38894251  0.30898608 -1.77646276
   1.91530967  0.21214434]
 [-0.34588212  2.41704809  1.2947494  -0.12419127  0.03973829  2.26057623
   0.64494489  2.5

In [7]:
#转置
stock_change.T

array([[ 0.23663317,  0.18406849, -0.0133358 ,  0.44063958, -0.12929875,
         0.53087326,  0.09788457,  0.60416388,  2.43488565, -0.34588212],
       [ 0.03488579, -0.30681789,  0.4303031 ,  0.74478827, -1.20058572,
        -0.40326097,  0.86054786, -0.09395627, -0.50830003,  2.41704809],
       [ 0.35633464, -0.32267767,  2.35476663, -0.45848981,  0.81434476,
        -2.06977153, -0.98554366,  1.33481531,  1.35430645,  1.2947494 ],
       [ 1.13028114, -1.1431804 , -0.25158349,  1.13889807,  0.24637811,
         0.5430819 ,  1.00046056,  0.17421221,  0.38894251, -0.12419127],
       [ 0.6015624 , -0.79222112, -1.03822626, -0.3113159 , -1.55279182,
         2.80880493, -0.18483511,  0.76928918,  0.30898608,  0.03973829],
       [ 0.39097332, -0.05054762,  0.92226543,  2.33507508, -0.02552282,
         1.11240915,  1.3025589 ,  0.13996727, -1.77646276,  2.26057623],
       [ 0.04637329,  0.31163214,  0.25972792,  0.89605235, -0.22109037,
        -0.33263886, -0.46337703,  0.15429646

In [8]:
#一维化
stock_change.flatten()

array([ 0.23663317,  0.03488579,  0.35633464,  1.13028114,  0.6015624 ,
        0.39097332,  0.04637329,  1.77251388,  0.18406849, -0.30681789,
       -0.32267767, -1.1431804 , -0.79222112, -0.05054762,  0.31163214,
       -1.47027098, -0.0133358 ,  0.4303031 ,  2.35476663, -0.25158349,
       -1.03822626,  0.92226543,  0.25972792, -0.45337474,  0.44063958,
        0.74478827, -0.45848981,  1.13889807, -0.3113159 ,  2.33507508,
        0.89605235,  0.5250052 , -0.12929875, -1.20058572,  0.81434476,
        0.24637811, -1.55279182, -0.02552282, -0.22109037, -0.77157018,
        0.53087326, -0.40326097, -2.06977153,  0.5430819 ,  2.80880493,
        1.11240915, -0.33263886, -0.92186257,  0.09788457,  0.86054786,
       -0.98554366,  1.00046056, -0.18483511,  1.3025589 , -0.46337703,
       -1.07795541,  0.60416388, -0.09395627,  1.33481531,  0.17421221,
        0.76928918,  0.13996727,  0.15429646,  0.00824792,  2.43488565,
       -0.50830003,  1.35430645,  0.38894251,  0.30898608, -1.77