NumPy-矩阵运算

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#矩阵的存储

#期中和期末成绩（8*2矩阵）
#np.array()
grade=np.array([[80,86],
                  [82,80],
                  [85,78],
                  [90,90],
                  [86,82],
                  [82,90],
                  [78,80],
                  [92,94]])
print(grade)
print(type(grade))

#np.mat()
grade_mat=np.mat(grade)
print(grade_mat)
print(type(grade_mat))

'''
两者的区别在于矩阵必须是二维数组的形式，而ndarray可以是任意维度的。
'''

[[80 86]
 [82 80]
 [85 78]
 [90 90]
 [86 82]
 [82 90]
 [78 80]
 [92 94]]
<class 'numpy.ndarray'>
[[80 86]
 [82 80]
 [85 78]
 [90 90]
 [86 82]
 [82 90]
 [78 80]
 [92 94]]
<class 'numpy.matrix'>


'\n两者的区别在于矩阵必须是二维数组的形式，而ndarray可以是任意维度的。\n'

In [3]:
#矩阵乘法

#成绩权重（2*1矩阵）
weights=np.array([[0.3],[0.7]])

#矩阵乘法计算总成绩

#ndarray类型的矩阵乘法
#np.matmul()
print(np.matmul(grade, weights))
#np.dot()
print(np.dot(grade, weights))
#用@计算矩阵乘法
print(grade@weights)

#matrix类型的矩阵乘法（直接相乘）
weights_mat=np.mat(weights)
print(grade_mat*weights_mat)

[[84.2]
 [80.6]
 [80.1]
 [90. ]
 [83.2]
 [87.6]
 [79.4]
 [93.4]]
[[84.2]
 [80.6]
 [80.1]
 [90. ]
 [83.2]
 [87.6]
 [79.4]
 [93.4]]
[[84.2]
 [80.6]
 [80.1]
 [90. ]
 [83.2]
 [87.6]
 [79.4]
 [93.4]]
[[84.2]
 [80.6]
 [80.1]
 [90. ]
 [83.2]
 [87.6]
 [79.4]
 [93.4]]
