NumPy-数组的合并与分割

In [1]:
#导入NumPy包
import numpy as np

In [2]:
#数组的水平合并

a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.hstack((a,b)))
c=np.array([[1],[2],[3]])
d=np.array([[4],[5],[6]])
print(np.hstack((c,d)))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [3]:
#数组的垂直合并

a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
c=np.array([[1],[2],[3]])
d=np.array([[4],[5],[6]])
print(np.vstack((c,d)))

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
#np.concatenate()

a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
#数组的水平合并
print(np.concatenate((a,b.T),axis=1))
#数组的垂直合并
print(np.concatenate((a,b),axis=0))

[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
#数组的分割

#生成等差数组
x=np.arange(9)
print(x)

#等长度分割
print(np.split(x,3))

#按索引位置分割
print(np.split(x,[3,5,6,9]))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([], dtype=int32)]
